# Copyright IBM Corp. 2013, 2026
# SPDX-License-Identifier: MPL-2.0


variable "project" {
  type    = string
  default = "${env("GOOGLE_PROJECT_ID")}"
}

variable "service_account_file" {
  type    = string
  default = "${env("GOOGLE_APPLICATION_CREDENTIALS")}"
}

variable "ssh_username" {
  type    = string
  default = "packer"
}

variable "region" {
  type    = string
  default = "us-central1"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "googlecompute" "autogenerated_1" {
  account_file        = var.service_account_file
  image_name          = "packer-bulk-tester-${local.timestamp}"
  project_id          = "${var.project}"
  source_image_family = "centos-stream-9"
  ssh_username        = "${var.ssh_username}"
  skip_create_image   = true
  use_bulk_api        = true
  region              = "${var.region}"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    inline = ["echo provisioner ran"]
  }
}
